ConsumirAPI/Controllers/ClienteController.cs
using ConsumirAPI.Models;
using ConsumirAPI.Servicios;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumirAPI.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IServicesAPI _servicesAPI;

        public ClienteController(IServicesAPI servicioAPI)
        {
            _servicesAPI = servicioAPI;
        }
        public IActionResult CrearC()
        {
            return View();
        }

        public async Task<IActionResult> ObtenerC()
        {
            List<ModeloCliente> lista = await _servicesAPI.ListarC();

            return Json(new { data = lista });
        }


        public async Task<IActionResult> GuardarC(ModeloCliente ObjCat)
        {
            bool respuesta = false;

            //      Console.WriteLine(ObjCat);

            if (ObjCat.Id == Guid.Empty)
            {

                respuesta = await _servicesAPI.InsertarC(ObjCat);
            }
            else
            {
                respuesta = await _servicesAPI.EditarC(ObjCat);
            }
            return Json(new { resultado = respuesta });
        }

        public async Task<IActionResult> EliminarC(Guid Id)
        {
            bool respuesta = false;

            Console.WriteLine(Id);

            if (Id != Guid.Empty)
            {

                respuesta = await _servicesAPI.DeleteC(Id);
            }

            return Json(new { resultado = respuesta });
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumirAPI/Controllers/RolController.cs
using ConsumirAPI.Models;
using ConsumirAPI.Servicios;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumirAPI.Controllers
{
    public class RolController : Controller
    {
        private readonly IServicesAPI _servicesAPI;

        public RolController(IServicesAPI servicioAPI)
        {
            _servicesAPI = servicioAPI;
        }
        public IActionResult CrearRol()
        {
            return View();
        }

        public async Task<IActionResult> ObtenerR()
        {
         
            List<ModeloRol> lista = await _servicesAPI.Listar();

            return Json(new { data = lista });
        }


        public async Task<IActionResult> GuardarR(ModeloRol ObjRol)
        {
            bool respuesta = false;

                //Console.WriteLine(ObjRol);

            if (ObjRol.Id == Guid.Empty)
            {

                respuesta = await _servicesAPI.InsertarR(ObjRol);
            }
            else
            {
                respuesta = await _servicesAPI.EditarRol(ObjRol);
            }
            return Json(new { resultado = respuesta });
        }

        public async Task<IActionResult> EliminarR(Guid Id)
        {
            bool respuesta = false;

            Console.WriteLine(Id);

            if (Id != Guid.Empty)
            {

                respuesta = await _servicesAPI.DeleteR(Id);
            }

            return Json(new { resultado = respuesta });
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumirAPI/Controllers/UMedidaController.cs
using ConsumirAPI.Models;
using ConsumirAPI.Servicios;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumirAPI.Controllers
{
    public class UMedidaController : Controller
    {
        private readonly IServicesAPI _servicesAPI;

        public UMedidaController(IServicesAPI servicioAPI)
        {
            _servicesAPI = servicioAPI;
        }
        public IActionResult CrearU()
        {
            return View();
        }

        public async Task<IActionResult> ObtenerU()
        {
            List<ModeloUMedida> lista = await _servicesAPI.ListaU();

            return Json(new { data = lista });
        }


        public async Task<IActionResult> GuardarU(ModeloUMedida ObjU)
        {
            bool respuesta = false;


            if (ObjU.Id == Guid.Empty)
            {

                respuesta = await _servicesAPI.InsertarU(ObjU);
            }
            else
            {
                respuesta = await _servicesAPI.EditarU(ObjU);
            }
            return Json(new { resultado = respuesta });
        }

        public async Task<IActionResult> EliminaU(Guid Id)
        {
            bool respuesta = false;

            Console.WriteLine(Id);

            if (Id != Guid.Empty)
            {

                respuesta = await _servicesAPI.DeleteU(Id);
            }

            return Json(new { resultado = respuesta });
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumirAPI/Controllers/UsuarioController.cs
using ConsumirAPI.Models;
using ConsumirAPI.Servicios;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumirAPI.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IServicesAPI _servicesAPI;

        public UsuarioController(IServicesAPI servicioAPI)
        {
            _servicesAPI = servicioAPI;
        }
        public IActionResult CrearUs()
        {
            return View();
        }

        public async Task<IActionResult> ObtenerUs()
        {
            List<ModeloUsuario> lista = await _servicesAPI.ListaUs();

            return Json(new { data = lista });
        }


        public async Task<IActionResult> GuardarUs(ModeloUsuario ObjU)
        {
            bool respuesta = false;


            if (ObjU.Id == Guid.Empty)
            {

                respuesta = await _servicesAPI.InsertarUs(ObjU);
            }
            else
            {
                respuesta = await _servicesAPI.EditarUs(ObjU);
            }
            return Json(new { resultado = respuesta });
        }

        public async Task<IActionResult> EliminaUs(Guid Id)
        {
            bool respuesta = false;

            Console.WriteLine(Id);

            if (Id != Guid.Empty)
            {

                respuesta = await _servicesAPI.DeleteUs(Id);
            }

            return Json(new { resultado = respuesta });
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ConsumirAPI/Views/Shared/ACatalogos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Interfaz</title>

    <link rel="stylesheet" href="~/bootstrap-5.0.2-dist/Alpha/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/sweetalert2.css" />
    <link rel="stylesheet" type="text/css" href="~/bootstrap-5.0.2-dist/Alpha/Alpha1/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/DataTables/DataTables-1.13.6/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumirAPI.styles.css" asp-append-version="true" />


</head>
<body>
    <header>
        <!DOCTYPE html>
        <html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Plantilla de Insumos Barrera</title>

        </head>
        <body style="background-color: #D3D3D3;">

            <!-- Barra de navegación -->
            <nav class="navbar" style="background-color: #4169E1;">
                <div class="container">
                    <div class="navbar-left">
                        <a href="Home">
                            <img class="navbar-logo" src="https://images.vexels.com/media/users/3/235848/isolated/preview/4b62529b242dcef2dbc6719899ecdd6e-gorro-de-cocinero-de-cocina.png" alt="Logo">
                        </a>
                    </div>
                    <div class="navbar-center">
                        <a class="navbar-brand text-white negrita" href="//localhost:7118">
                            Insumos Barrera
                        </a>
                    </div>
                </div>
            </nav>


            <div>
                <br />
                <header class="masthead bg-primary text-white text-center">
                    <!-- Masthead Subheading-->
                    <p class="masthead-subheading font-weight-light mb-0 text-white">Gestión de Catalogos</p>
            </div>
            <div class="content" style="background-color: #D3D3D3;">

              @*   <div class="logo">
                    <!-- Aquí puedes insertar el logotipo de tu empresa -->
                    <img class="masthead-avatar mb-1" src="https://images.vexels.com/media/users/3/235848/isolated/preview/4b62529b242dcef2dbc6719899ecdd6e-gorro-de-cocinero-de-cocina.png" alt="..." />
                    <!-- Fin-->
                </div> *@


                <div class="contact-form text-white">
                    <h2></h2>

                    <div class="espacio"></div>

                        <nav class="navbar" style="background-color: #4169E1;">
                            <div class="container">
                    <ul class="nav-list">
                    <form id="login-form">
                        
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Categoria" asp-action="Crear">Categoria</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Categoria" asp-action="Crear">Inventario</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="UMedida" asp-action="CrearU">Unidad de Medida</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="CrearUs">Usuario</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Categoria" asp-action="Crear">Producto</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Cliente" asp-action="CrearC">Cliente</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Rol" asp-action="CrearRol">Rol</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Categoria" asp-action="Crear">Detalle Producto</a></li>
                        <li><a class="nav-link text-white" asp-area="" asp-controller="Proveedor" asp-action="CrearP">Proveedor</a></li>
                                <li><a class="nav-link text-white" asp-area="" asp-controller="Facturacion" asp-action="Index">Facturacion</a></li>
                    </form>
                        </ul>
                        <nav>
                    </div>
                </div>
        </body>
    </html>

</header>

</body>
</html>

ConsumirAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Interfaz</title>

    <link rel="stylesheet" href="~/bootstrap-5.0.2-dist/Alpha/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/sweetalert2.css" />
    <link rel="stylesheet" type="text/css" href="~/bootstrap-5.0.2-dist/Alpha/Alpha1/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/DataTables/DataTables-1.13.6/css/dataTables.bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumirAPI.styles.css" asp-append-version="true" />


</head>
<body style="background-color: #D3D3D3;">
    @{
        var currentAction = ViewContext.RouteData.Values["action"].ToString().ToLowerInvariant();
    }
    @if (currentAction == "index" || currentAction == "")
    {
        <!-- Barra de navegación -->
        <nav class="navbar" style="background-color: #4169E1;">
            <div class="container">
                <div class="navbar-left">
                    <a href="Home">
                        <img class="navbar-logo" src="https://images.vexels.com/media/users/3/235848/isolated/preview/4b62529b242dcef2dbc6719899ecdd6e-gorro-de-cocinero-de-cocina.png" alt="Logo">
                    </a>
                </div>
                <div class="navbar-center">
                    <a class="navbar-brand text-white negrita" href="Home">
                        Insumos Barrera
                    </a>
                </div>
            </div>
        </nav>


        <br />
        <header class="masthead bg-primary text-white text-center">
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0 text-white">Bienvenidos</p>
        </header>

        <div class="espacio"></div>

        <!-- Contenido principal -->
        <div class="content" style="background-color: #D3D3D3;">


            <div class="logo">
                <!-- Aquí puedes insertar el logotipo de tu empresa -->
                <img class="masthead-avatar mb-1" src="https://images.vexels.com/media/users/3/235848/isolated/preview/4b62529b242dcef2dbc6719899ecdd6e-gorro-de-cocinero-de-cocina.png" alt="Logo" />
                <!-- Fin-->
            </div>


            <div class="modal fade" id="LoginFormModal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header btn-info text-whide">
                            <h5 class="modal-title text-white" id="exampleModalLabel">Iniciar Sesión</h5>
                            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="contact-form text-white">
                                @* <h2>Iniciar sesión</h2> *@

                                <form id="login-form" method="get">
                                    <input type="text" placeholder="Usuario">
                                    <input type="password" placeholder="Contraseña">
                                    <li><a class="nav-link text-white">Otro</a></li>
                                    <button asp-controller="Home" asp-action="Redireccionando">Enviar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
        <div class="modal fade" id="RegisterFormModal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header btn-info text-whide">
                        <h5 class="modal-title text-white" id="exampleModalLabel">Registrarse</h5>
                        <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="contact-form text-white">
                            @*   <h2>Registrarse</h2> *@

                            <form id="login-form" method="get">
                                <input type="text" placeholder="Usuario">
                                <input type="password" placeholder="Contraseña">
                                <input type="password" placeholder="Confirmar Contraseña">
                                <li><a class="nav-link text-white">Otro</a></li>
                                <button asp-controller="Home" asp-action="Redireccionando">Enviar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="centrarDiv">
            <button id="iniciarBtn" class="boton-azul">Iniciar Sesión</button>

            <button id="registrarBtn" class="boton-azul">Registrarse</button>
        </div>


        <script>
            document.getElementById('iniciarBtn').addEventListener('click', function () {
                $('#LoginFormModal').modal('show');
            });
        </script>

        <script>
            document.getElementById('registrarBtn').addEventListener('click', function () {
                $('#RegisterFormModal').modal('show');
            });
        </script>


        <div class="espacio"></div>

        <nav class="navbar" style="background-color: #4169E1;">
            <div class="container d-flex flex-column align-items-center text-center text-white">
                <h3>"Acerca de Insumos Barrera"</h3>
                <p>Insumos Barrea es una empresa que ha venido creciendo con el paso del tiempo de manera favorable, garantizando fidelidad y compromiso con sus clientes.</p>
                <p>"Nos puedes ubicar de la sorbeteria herrera 1 cuadra al oeste media al sur, Para mayor información nos puedes llamar al numero 29873289"</p>
            </div>
        </nav>


    }


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/sweetalert2.all.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script type="text/javascript" src="~/DataTables/JsZip-3.10.1/jszip.min.js"></script>
    <script type="text/javascript" src="~/DataTables/pdfmake-0.2.7/pdfmake.min.js"></script>
    <script type="text/javascript" src="~/DataTables/pdfmake-0.2.7/vfs_fonts.js"></script>
    <script type="text/javascript" src="~/DataTables/Datatables-1.13.6/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/DataTables/DataTables-1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons.bootstrap5.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons.colVis.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="~/DataTables/Buttons-2.4.2/js/buttons.print.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>